baseURL = 'https://lpe234.xyz/'

languageCode = 'zh-CN'
timeZone = 'Asia/Shanghai'

title = 'Lp+Yj->LY'

#
theme = 'hello-friend'
summaryLength = 200
#
pagination.pagerSize = 10
rssLimit = 5

[permalinks]
posts = "/posts/:filename/"
tags = "/tags/:slug/"

[params]
# "light" or "dark"
defaultTheme = "light"
showReadingTime = true

MenuMore = "æ›´å¤š"
DateFormatList = "2006-01-02"
DateFormatSingle = "2006-01-02"
ReadMore = "é˜…è¯»å…¨æ–‡"

description = "è·¯æ¼«æ¼«å…¶ä¿®è¿œå…®"
keywords = "åšå®¢ã€ç¼–ç ã€æŠ˜è…¾ã€ç”Ÿæ´»ã€é˜…è¯»ã€è‡ªå¾‹"

[menu]
[[menu.main]]
name = "ç¼–ç "
url = "/posts/coding/"
weight = "10"
[[menu.main]]
name = "è¯»ä¹¦"
url = "/posts/reading/"
weight = "20"
[[menu.main]]
name = "é—²èŠ"
url = "/posts/chat/"
weight = "30"
[[menu.main]]
name = "å½’æ¡£"
url = "/archives/"
weight = "40"
[[menu.main]]
name = "å…³äºæˆ‘"
url = "/about/"
weight = "50"
[[menu.main]]
name = "ğŸ”"
url = "/search/"
weight = "60"

[outputs]
home = ["Atom", "HTML", "JSON"] # <domain>/atom.xml
page = ["HTML"]

[outputFormats.Atom]
mediatype = "application/rss"
baseName = "atom"

[params.twikoo]
enable = false
visitor = true
